### ISSUE TITLE
数据库部分没有理论巨著

### ISSUE THREAD

**Issue by noisnemid** [jobbole/awesome-programming-books#16]
如题，全是应用啊sql啊，哪怕列一本《数据库系统概念》，最差也得有本《数据库系统概论》啊，数据库理论和原理比较特殊，它的地位应该提到几乎与算法数据结构平等的层次上来。

**Comment by leafonsword** [comment]
赞成

**Comment by huanglimin** [comment]
谢谢补充，列表中已添加《数据库系统概念》和《数据库系统实现》
