### ISSUE TITLE
为什么没有Pull Request呢？

### ISSUE THREAD

**Issue by plugine** [jobbole/awesome-programming-books#6]
关注这个项目几天了，也有几本书单中没有列及的经典书籍欲推荐，可乍一看并没有人提出Pull Request，贡献者只有一个。文中链接皆为京东联盟链接，这是想提pl也不敢提的，求伯乐在线的朋友解释一下。

**Comment by huanglimin** [comment]
你好，

1. 有几位是在 Issues 推荐了；
2. 请问你对联盟链接的担心是什么？
3. 关于联盟链接，这挺正常的，豆瓣读书就加了。

**Comment by plugine** [comment]
谢谢你的耐心解答~
